repos:
  - repo: https://github.com/pycqa/isort
    rev: "6.0.0"
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: "25.1.0"
    hooks:
      - id: black
  - repo: https://github.com/pycqa/flake8
    rev: "7.1.2"
    hooks:
      - id: flake8
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.19.1
    hooks:
    -   id: pyupgrade
  - repo: https://github.com/adamchainz/django-upgrade
    rev: "1.23.1"  # replace with latest tag on GitHub
    hooks:
    -   id: django-upgrade
        args: [--target-version, "5.0"]   # Replace with Django version
  - repo: https://github.com/python-poetry/poetry
    rev: "1.8.3"  # add version here
    hooks:
    -   id: poetry-check
    -   id: poetry-export
    -   id: poetry-install
